### ISSUE TITLE
Representing Htmx validation

### ISSUE THREAD

**Issue by MarcCoquand** [yawaramin/dream-html#17]
Heya!

I'm trying to figure out how you would represent Htmx validations in the library.

In the usage examples https://htmx.org/docs/#validation-example, it looks like it should be something like this:

```
<form id="example-form" hx-post="/test">
    <input name="example"
           onkeyup="this.setCustomValidity('') // reset the validation on keyup"
           hx-on:htmx:validation:validate="if(this.value != 'foo') {
                    this.setCustomValidity('Please enter the value foo') // set the validation error
                    htmx.find('#foo-form').reportValidity()              // report the issue
                }">
</form>
```
However, I can't find any Hx.on_htmx_validation_validate or similar function. Has it maybe not been implemented?

**Comment by yawaramin** [comment]
Hello, since `hx-on:` supports any arbitrary DOM event, and not only htmx events, it doesn't make sense to wrap all of them in this library (imho). So you can pass the event name as a string:

```ocaml
Hx.on_ "htmx:validation:validate" {|
  // handle
|}
```

As per https://yawaramin.github.io/dream-html/dream-html/Dream_html/Hx/index.html#val-on_

Also remember that `hx-on:` is purely a convenience. You can always just use standard web APIs here:

```ocaml
script [] {|
  document.getElementById('example-form').addEventListener(...)
|}
```

**Comment by MarcCoquand** [comment]
Ah great! Thank you for the examples
